import { ApiProperty } from '@nestjs/swagger';
import { IsString, MaxLength, MinLength } from 'class-validator';

export class VkPrepareDto {
  @ApiProperty({
    description: 'OAuth state generated by the client (UUID recommended)',
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
  @IsString()
  @MinLength(16)
  @MaxLength(128)
  state!: string;
}
