import { type BookingMetricsService } from './booking-metrics.service';

export function createBookingMetricsMock(): BookingMetricsService {
  return {
    recordBookingCreated: jest.fn(),
    observeBookingCreationDuration: jest.fn(),
    recordBookingExpired: jest.fn(),
    recordBookingCanceled: jest.fn(),
    recordOperationFailed: jest.fn(),
    recordCreateCompensationFailed: jest.fn(),
    recordTicketingFailureEscalated: jest.fn(),
    recordTicketingFailureEscalationFailed: jest.fn(),
    recordCheckoutStarted: jest.fn(),
    recordCheckoutCompleted: jest.fn(),
    recordCheckoutFailed: jest.fn(),
    observeCheckoutDuration: jest.fn(),
    recordCheckoutRollback: jest.fn(),
    recordTravelersAdded: jest.fn(),
    recordTravelerValidationFailed: jest.fn(),
    recordSeatAssignment: jest.fn(),
    observeSeatAssignmentDuration: jest.fn(),
    recordSeatAssignmentFailed: jest.fn(),
    recordSeatHoldRefreshed: jest.fn(),
    recordSeatRelease: jest.fn(),
    recordInventoryReserved: jest.fn(),
    recordInventoryReleased: jest.fn(),
    recordInventoryReservationFailed: jest.fn(),
    recordOutboxEnqueued: jest.fn(),
    recordOutboxSent: jest.fn(),
    recordOutboxRetry: jest.fn(),
    recordOutboxFailed: jest.fn(),
    recordMaintenanceRun: jest.fn(),
    observeMaintenanceDuration: jest.fn(),
    recordMaintenanceItemsProcessed: jest.fn(),
    recordCacheHit: jest.fn(),
    recordCacheMiss: jest.fn(),
    recordCacheInvalidation: jest.fn(),
    recordTicketDownload: jest.fn(),
  } as unknown as BookingMetricsService;
}
